### ISSUE TITLE
Link typo in README

### ISSUE THREAD

**Issue by narze** [dtinth/advent-of-code-2022#1]
`[build task](./vscode/tasks.json)` -> `[build task](.vscode/tasks.json)`

**Comment by narze** [comment]
btw, congrats on 1st rank on day 4! 🎉

**Comment by dtinth** [comment]
Thanks! Fixed in https://github.com/dtinth/advent-of-code-2022/commit/8fd53b3849feec251e4c35b25e41b5db58d3696b
